BackEndCapstone/Controllers/ProfileController.cs
using BackEndCapstone.Data;
using BackEndCapstone.Models;
using BackEndCapstone.Models.RegistrationViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BackEndCapstone.Controllers
{
    public class ProfileController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public ProfileController(ApplicationDbContext ctx,
                          UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = ctx;
        }
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);


        public async Task<IActionResult> Index(UploadProfilePicViewModel viewModel)
        {
            viewModel.IUsers = _context.ApplicationUsers.Include(w => w.WatchParties).Include(p => p.PartyAttendees) ;
            viewModel.watchParty = _context.WatchParty.Include(u => u.User).Include(p => p.PartyAttendees).Include(t => t.Team);
            var currentuser = await GetCurrentUserAsync();
            ViewData["CurrentUser"] = currentuser;


            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UploadProfilePicViewModel viewModel)
        {
            var currentuser = await GetCurrentUserAsync();
            var User = await _context.ApplicationUsers.FindAsync(currentuser.Id);

            ModelState.Remove("viewModel.Id");

                if (viewModel.ImageFile != null)
                {
                    var fileName = Path.GetFileName(viewModel.ImageFile.FileName);
                    Path.GetTempFileName();
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images/userprofilepic", fileName);
                   
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await viewModel.ImageFile.CopyToAsync(stream);
                    }

                    User.ImagePath = viewModel.ImageFile.FileName;
                }


                _context.Update(User);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
        }

        public async Task<IActionResult> EditWatchParty(int? id)
        {
            ViewData["TeamId"] = new SelectList(_context.Team, "TeamId", "Name");
            if (id == null)
            {
                return NotFound();
            }

            var watchParty = await _context.WatchParty
                .Include(w => w.User)
                .Include(t => t.Team)
                .FirstOrDefaultAsync(m => m.WatchPartyId == id);
            if (watchParty == null)
            {
                return NotFound();
            }
            
            return View(watchParty);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditWatchParty(int id, [Bind("WatchPartyId,Title,Description,Address,Limit,Date,UserId,ImagePath,TeamId")] WatchParty watchParty)
        {
            
            if (id != watchParty.WatchPartyId)
            {
                return NotFound();
            }
            ModelState.Remove("UserId");

            var currentuser = await GetCurrentUserAsync();

            if (ModelState.IsValid)
            {
                watchParty.UserId = currentuser.Id;

                    _context.Update(watchParty);
                    await _context.SaveChangesAsync();
                
                
                return RedirectToAction(nameof(Index));
            }
            
            return View(watchParty);
        }

        // GET: WatchParties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var watchParty = await _context.WatchParty
                .Include(w => w.User)
                .FirstOrDefaultAsync(m => m.WatchPartyId == id);
            if (watchParty == null)
            {
                return NotFound();
            }

            return View(watchParty);
        }

        // POST: WatchParties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var watchParty = await _context.WatchParty.FindAsync(id);
            var attendees = _context.PartyAttendee.Where(pa => pa.WatchPartyId == id);

            foreach (var x in attendees)
            {
              _context.PartyAttendee.Remove(x);
            }
            
            _context.WatchParty.Remove(watchParty);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

BackEndCapstone/Controllers/WatchPartiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BackEndCapstone.Data;
using BackEndCapstone.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using BackEndCapstone.Models.WatchPartyViewModels;
using System.IO;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BackEndCapstone.Controllers
{
    public class WatchPartiesController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;
       
        public WatchPartiesController(ApplicationDbContext ctx,
                          UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = ctx;
        }
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        


        // GET: WatchParties
        public async Task<IActionResult> Index(string SelectedTeam, IndexViewModel watchParty)
        {
            ViewData["TeamId"] = new SelectList(_context.Team, "Name", "Name");
            if (SelectedTeam != null)
            {
                watchParty.WatchParties = _context.WatchParty
                    .Include(w => w.User)
                    .Include(t => t.Team)
                    .Where(tt => tt.Team.Name == SelectedTeam)
                    .OrderByDescending(p => p.Date);
                return View(watchParty);
            }
            else if (SelectedTeam == "" || SelectedTeam == null)
            {
                watchParty.WatchParties = _context.WatchParty.Include(w => w.User).Include(t => t.Team);
                return View(watchParty);
            }
            return View(watchParty);
        }

        // GET: WatchParties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var watchParty = await _context.WatchParty
                .Include(w => w.User)
                .Include(t => t.Team)
                .FirstOrDefaultAsync(m => m.WatchPartyId == id);
            if (watchParty == null)
            {
                return NotFound();
            }

            var attendees = _context.PartyAttendee.Where(pa => pa.WatchPartyId == id);
            var currentUser = await GetCurrentUserAsync();

            foreach(var x in attendees)
            {
                if (x.UserId == currentUser.Id)
                {
                    ViewData["attendee"] = x;
                }
            }

            return View(watchParty);
        }

        // GET: WatchParties/Create
        public IActionResult Create()
        {
            UploadWatchPartyPicViewModel viewModel = new UploadWatchPartyPicViewModel();
            viewModel.watchParty = new WatchParty();
            ViewData["TeamId"] = new SelectList(_context.Team, "TeamId", "Name");
            
            return View(viewModel);
        }

        // POST: WatchParties/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UploadWatchPartyPicViewModel viewModel)
        {
            ModelState.Remove("watchParty.UserId");

            // adding current userId
            var user = await GetCurrentUserAsync();
            viewModel.watchParty.UserId = user.Id;


            if (ModelState.IsValid)
            {
                if (viewModel.ImageFile != null)
                {
                    // don't rely on or trust the FileName property without validation
                    //**Warning**: The following code uses `GetTempFileName`, which throws
                    // an `IOException` if more than 65535 files are created without 
                    // deleting previous temporary files. A real app should either delete
                    // temporary files or use `GetTempPath` and `GetRandomFileName` 
                    // to create temporary file names.
                    var fileName = Path.GetFileName(viewModel.ImageFile.FileName);
                    Path.GetTempFileName();
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images/partypic", fileName);
                    //var filePath = Path.GetTempFileName();
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await viewModel.ImageFile.CopyToAsync(stream);
                        // validate file, then move to CDN or public folder
                    }

                    viewModel.watchParty.ImagePath = viewModel.ImageFile.FileName;
                }




                _context.Add(viewModel.watchParty);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            ViewData["TeamId"] = new SelectList(_context.Team, "TeamId", "Name", viewModel.watchParty.TeamId);

            return View(viewModel.watchParty);
        }

        // GET: WatchParties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var watchParty = await _context.WatchParty.FindAsync(id);
            if (watchParty == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", watchParty.UserId);
            return View(watchParty);
        }

        // POST: WatchParties/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WatchPartyId,Title,Description,Address,Limit,Date,UserId,ImagePath,TeamId")] WatchParty watchParty)
        {
            if (id != watchParty.WatchPartyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(watchParty);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WatchPartyExists(watchParty.WatchPartyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", watchParty.UserId);
            return View(watchParty);
        }

        // GET: WatchParties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var watchParty = await _context.WatchParty
                .Include(w => w.User)
                .FirstOrDefaultAsync(m => m.WatchPartyId == id);
            if (watchParty == null)
            {
                return NotFound();
            }

            return View(watchParty);
        }

        // POST: WatchParties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var watchParty = await _context.WatchParty.FindAsync(id);
            _context.WatchParty.Remove(watchParty);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WatchPartyExists(int id)
        {
            return _context.WatchParty.Any(e => e.WatchPartyId == id);
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> AttendWatchParty( int WatchPartyId)
        {
            

           PartyAttendee partyAttendee = new PartyAttendee();
            var user = await GetCurrentUserAsync();
            var watchParty = _context.WatchParty.Where(p => p.WatchPartyId == WatchPartyId ).Include(p => p.PartyAttendees).FirstOrDefault();
            var attendees = watchParty.PartyAttendees.Select(s => s.UserId);
           var id = WatchPartyId;
            var msg = "You are already going!";


                if (attendees.Contains(user.Id)) {
                ViewBag.Message = msg;
                ViewBag.Message = msg;
                return RedirectToAction("Details", new { Id = id });
            } 
                else
                {
                    partyAttendee.UserId = user.Id;
                    partyAttendee.WatchPartyId = watchParty.WatchPartyId;

                    
                        watchParty.Limit = watchParty.Limit - 1;
                        _context.Add(partyAttendee);
                        await _context.SaveChangesAsync();
                    return RedirectToAction("Details", new { Id = id });
                

                }

        }

        public async Task<IActionResult> CancelAttendance(int WatchPartyId)
        {
            var id = WatchPartyId;
            var attendees = _context.PartyAttendee.Where(pa => pa.WatchPartyId == id);
            var currentUser = await GetCurrentUserAsync();
            var WatchParty = _context.WatchParty.Where(w => w.WatchPartyId == id).FirstOrDefault(); 

            foreach (var x in attendees)
            {

BackEndCapstone/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BackEndCapstone</title>
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>


    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body id="page-top">
    <header>
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light sticky-top" id="mainNav">
            <div class="container">

                <a class="navbar-brand js-scroll-trigger">Huddle Up</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                @if (SignInManager.IsSignedIn(User))
                {<div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav text-uppercase ml-auto">
                            <li class="nav-item">
                                <a class="nav-link js-scroll-trigger" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link js-scroll-trigger" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link js-scroll-trigger" asp-area="" asp-controller="WatchParties" asp-action="Create">Host A Watch Party!</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link js-scroll-trigger" asp-area="" asp-controller="WatchParties" asp-action="Index">Find a Watch Party!</a>
                            </li>

                            <li class="nav-item">
                                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button type="submit" class="nav-link btn btn-link text-light ">Logout</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                }
                else
                {
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav text-uppercase ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </li>
                        </ul>
                    </div>
                }

            </div>
</nav>

    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Huddle Up - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>